version: '3'

services:
  web:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres@db
      TYPESENSE_URL: http://typesense:8108
      TYPESENSE_API_KEY: trust
    ports:
      - '3000:3000'
    depends_on:
      - db
      - typesense

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  # Typesense requires a data directory which must exist
  typesense:
    image: typesense/typesense:0.23.1
    command: '--data-dir /data --api-key=trust'
    volumes:
      - typesense:/data

volumes:
  typesense:
