version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis:6379
      RAILS_ENV: development
    command: 'yarn dev'
    ports:
      - '3000:3000'
      - '3035:3035'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
      - redis
    # - elasticsearch

  redis:
    image: redis

# elasticsearch:
#   image: elasticsearch:7.17.0
#   environment:
#     - discovery.type=single-node
#   volumes:
#     - elasticsearch:/usr/share/elasticsearch/data


volumes:
  pgdata:
  node_modules:
# elasticsearch:
