FROM node:24.18.0-alpine AS node
FROM ruby:4.0.5-alpine

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN apk add --update --no-cache bash build-base tzdata postgresql-dev yarn curl gcompat yaml yaml-dev libffi-dev

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn
RUN yarn install --immutable

COPY . .

COPY docker/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000
EXPOSE 3035

CMD ["yarn", "dev"]

HEALTHCHECK --start-period=1s --start-interval=1s \
  CMD test -n "$SKIP_HEALTHCHECK" || curl -f http://localhost:3000/healthcheck || exit 1
