version: '3'

services:
  web:
    build: .
    command: 'yarn dev'
    environment: &common-env
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis:6379
      TYPESENSE_URL: http://typesense:8108
      TYPESENSE_API_KEY: trust
      S3_BUCKET: untitled-note-app-development
    env_file: .env
    ports:
      - '3000:3000'
      - '3035:3035'
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - typesense

  clockwork:
    build: .
    entrypoint: ''
    command: 'clockwork config/clockwork.rb'
    environment: *common-env
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis

  typesense:
    image: typesense/typesense:0.25.2
    command: '--data-dir /data --api-key=trust'
    volumes:
      - typesense:/data

volumes:
  pgdata:
  typesense:
