version: '3'

services:
  web:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis:6379
      S3_BUCKET: untitled-note-app-development
    env_file: .env
    command: 'yarn dev'
    ports:
      - '3000:3000'
      - '3035:3035'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  pgdata:
  node_modules:
