version: '3'

services:
  web:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres@db
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
