name: Deploy production

on: workflow_dispatch

jobs:
  deploy_production:
    name: 'Deploy production'
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: 12joan/build-and-push-image/.github/workflows/build-and-push-image.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    concurrency:
      group: deploy-production
      cancel-in-progress: true
