name: Deploy production

on: workflow_dispatch

jobs:
  deploy_production:
    name: 'Deploy production'
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-production
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
      - uses: 12joan/build-and-push-image@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
