name: Deploy to staging

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker-compose -f docker-compose.test.yml pull

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - run: docker-compose -f docker-compose.test.yml build

    - run: docker-compose -f docker-compose.test.yml run web sh -c 'rails db:setup && rails test'

  deploy_staging:
    needs: test
    if: ${{ github.ref == 'refs/heads/feature/redesign' }} # TODO: Change back to ref/heads/main
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - uses: zenato/docker-action@master
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        repository: ${{ secrets.REGISTRY_REPO }}
        registry: ${{ secrets.REGISTRY_URL }}
        tag: staging
