name: Frontend tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker compose up -d
    - run: yarn playwright install
    - run: yarn e2e
    - run: docker compose down
